name: Remove sensitive information
on:
  push:
    branches:
      - dev
jobs:
  remove-secrets:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Remove existing files with sensitive data
        run: |
          rm -f \
            ./Assets/Scripts/Spotify/Data/users.json \
            ./Assets/Scripts/Spotify/Data/spotify.config

      - name: Recreate spotify.config without sensitive data
        run: |
          echo "// Client secrets
CLIENT_ID=...
CLIENT_SECRET=...

// User configs
USERS_PATH=Assets/Scripts/Spotify/Data/users.json
TOKEN_REFRESH_THRESHOLD=300

// Server configs
SERVER_REDIRECT_URI=http://localhost:5543/callback
SERVER_PORT=5543" > ./Assets/Scripts/Spotify/Data/spotify.config

      - name: Recreate users.json as empty JSON array
        run: echo "[]" > ./Assets/Scripts/Spotify/Data/users.json

      - name: Commit files and push them
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add "./Assets/Scripts/Spotify/Data/users.json" "./Assets/Scripts/Spotify/Data/spotify.config"
          git commit -m "Overwrite existing secrets files" --allow-empty
          git push
